# Generated by Django 5.0.3 on 2024-03-16 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_itempedido_subtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('draft', 'Em preenchimento'), ('waiting', 'Aguardando'), ('cancelled', 'Cancelado'), ('done', 'Finalizado')], default='draft', max_length=10),
        ),
        migrations.AddField(
            model_name='produto',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='componente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='produto',
            name='pn',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='PN'),
        ),
        migrations.AddField(
            model_name='produto',
            name='sn',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='SN'),
        ),
    ]
